//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sikayet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayet_Tablo
    {
        public int Sikayet_Id { get; set; }
        public string Firma_Adi { get; set; }
        public string Firma_Personel { get; set; }
        public string Sikayet_Turu { get; set; }
        public string Sikayet_Aciklamasi { get; set; }
        public string Tel_No { get; set; }
        public string Sirket_Eposta { get; set; }
        public string Cozum_Not { get; set; }
        public string Sikayet_Olusturan { get; set; }
        public string Istek_Durumu { get; set; }
        public Nullable<System.DateTime> Baslangic_Tarihi { get; set; }
        public Nullable<System.DateTime> Bitis_Tarihi { get; set; }
        public byte[] Istek_Fotografi { get; set; }
    }
}
